config/routes.rb
Honeycomb::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :events, except: [:index]
    end
  end
  resources :events, only: [:index]
  match 'events' => "events#index", via: :options
  
  devise_for :users

  root to: "home#index"
end

app/models/chart_data.rb
class ChartData
  def initialize(events)
    @events = events
  end

  def pagevisit_by_month
    @events.group_by { |e| e.created_at.month }
  end

  def pagevisits_count_per_month
    pagevisit_by_month.transform_values { |p| p.count }
  end

  def densify
    data = pagevisits_count_per_month
    (data.keys.min..data.keys.max).each do |month|
      data[month] = data[month] || 0
    end
  end

  def sorted_densified
    densify.sort
  end

  def labeled_frequency_data
    sorted_densified.transform_keys { |m| Date::MONTHNAMES[m] }
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :generate_unique_key
  
  private

    def generate_unique_key
      self.update_attribute(:unique_key, SecureRandom.hex(6))
    end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::ApplicationController
  require 'uri'

  def create
    @event = Event.new(params.require(:event).permit(:name, :property_1, :property_2, :url))
    @user = User.find_by(unique_key: params[:unique_key])
    @event.user = @user
    @website = URI.parse(@event.url).host
    @event.website = @website

    if @event.save
      render json: @event
    else
      render json: {error: "didn't save"}, status: 500
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = current_user.events
    @pagevisit_chart_data = ChartData.new(@events.where(name: "page_visit"))
    @click_chart_data = ChartData.new(@events.where(name: "click"))
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/index.html.erb
<h2><%= "#{current_user.email}'s app metrics" %></h2>
<p><%= "Unique Key: #{current_user.unique_key}" %></p>

<canvas id="events" width="600" height="400"></canvas>
  <%= javascript_tag do %>
    var eventData = {
    labels: <%= escape_javascript @pagevisit_chart_data.labeled_frequency_data.keys.to_json %>,
    datasets: [
        {
            label: "Page Visits",
            fillColor: "rgba(220,220,220,0.2)",
            strokeColor: "rgba(220,220,220,1)",
            pointColor: "rgba(220,220,220,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(220,220,220,1)",
            data: <%= escape_javascript @pagevisit_chart_data.labeled_frequency_data.values.to_json %>
            },
        {
            label: "Clicks",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: <%= escape_javascript @click_chart_data.labeled_frequency_data.values.to_json %>
        }
        ]
    };
    var events= document.getElementById("events").getContext("2d");
    new Chart(events).Line(eventData);
  <% end %>

<% if current_user.email == "admin@example.com" %>
    <script>
    var unique_key = "b91982343c99"
    var endpoint = "http://localhost:3000/api/v1/events"

    var honeycomb = function(event_name, label, value) {
      var honey_event = {
        'event':
        {
          name: event_name,
          property_1: label,
          property_2: value,
          url: window.location.href
        },
        unique_key: unique_key
      }
      var honey_request = new XMLHttpRequest();
          honey_request.open("POST", endpoint, true);
          honey_request.setRequestHeader('Content-Type', 'application/json');
          honey_request.onreadystatechange = function() {

          };
          honey_request.send(JSON.stringify(honey_event));
    };
    honeycomb("pageview");
    </script>
    <a class="btn btn-success" style="" href="#" onClick="honeycomb('click', 'test', 'event');">Test Click</a>
<% end %>

app/views/home/index.html.erb
<div class="inner cover">
  <h1>Honeycomb</h1>
  <p class="lead">A general purpose analytics tool</p>
  <% if current_user %>
    <%= link_to "My Dashboard", events_path, method: :options, class: 'btn btn-lg btn-default' %>
  <% else %>
    <p>You need a Honeycomb account to continue</p>
    <%= link_to "Sign in", new_user_session_path, class: 'btn btn-lg btn-default' %>
    <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-lg btn-default' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Honeycomb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header">
        <%= link_to "Honeycomb", root_path, class: 'nav-link'%>

        <div class="pull-right user-info">
          <% if current_user %>
            <%= link_to "Dashboard", events_path, method: :options, class: 'nav-link' %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
          <% end %>
        </div>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class]"alert alert-warning">
        <button type="button" class="close" data-dismis="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>


    <div class="container container-body">
      <div class="inner cover center-block">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>